routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => true,
    'reset' => true,
    'login'=>false
]);

Route::get('/login', 'Auth\LoginController@showLoginForm')->name("login");
Route::post('/login', 'Auth\LoginController@login')->name("postlogin");
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', function () {
        return redirect()->route('home');
    });
	Route::get('/','HomeController@index')->name('home');
	Route::get('/profile','HomeController@indexProfile');
	Route::post('/profile','HomeController@storeProfile');
    Route::resource('barang','BarangController');
    Route::post('barang-import','BarangController@import')->name('import.barang');
    Route::resource('supplier','SupplierController');
    Route::resource('tipe','TipeController');
    Route::resource('user','UserController');
    Route::resource('forecasting','ForecastingController');
    Route::get('laporan_persediaan','PersediaanController@index');
    Route::get('laporan_persediaan/export_persediaan', 'PersediaanController@exportExcel')->name('persediaan.export');
    Route::get('laporan_persediaan/export_persediaan/all', 'PersediaanController@exportExcelAll')->name('persediaan.export.all');
    Route::get('laporan_penjualan','PenjualanController@index')->name('penjualan.index');
    Route::get('laporan_penjualan/create','PenjualanController@create')->name('penjualan.create');
    Route::post('laporan_penjualan/store','PenjualanController@store')->name('penjualan.store');
    Route::get('laporan_penjualan/edit/{id}','PenjualanController@edit')->name('penjualan.edit');
    Route::put('laporan_penjualan/update/{id}','PenjualanController@update')->name('penjualan.update');
    Route::post('laporan_penjualan/import','PenjualanController@import')->name('laporan_penjualan.import');
    Route::resource('laporan_pembelian','PembelianController');
    Route::get('export_pembelian', 'PembelianController@exportExcel')->name('pembelian.export');
    Route::get('export_pembelian/all', 'PembelianController@exportExcelAll')->name('pembelian.export.all');

    // Permisison
    Route::get('permission','PermissionController@index');
    Route::post('permission/request','PermissionController@requestPermission')->name('permission.request');
    Route::get('permission/accept/{id}','PermissionController@acceptPermission')->name('permission.accepted');
    Route::get('permission/decline/{id}','PermissionController@declinePermission')->name('permission.declined');
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $table = 'supplier';
    protected $fillable = [
        'nama','alamat','telpon'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public function scopeSearch($query, $search){
        if ($search){
            return $query->whereRaw("(upper(nama) like '%". strtoupper($search) ."%')");
        }
    }
}

app/Http/Controllers/SupplierController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Supplier;
use Illuminate\Support\Facades\Validator;

class SupplierController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('admin_gudang');
    }


    protected $customMessages = [
        'required' => ':attribute Harus Diisi',
        'unique' => ':attribute Sudah Ada Didatabase',
        'max' => ':attribute Max :max Digit',
        'min' => ':attribute Minimal :min',
    ];
    protected $customeAttr = [
        'nama' => 'nama',
        'telpon' => 'telpon',
        'alamat' => 'alamat',
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['datas'] = Supplier::get();
        return view('supplier.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        return view('supplier.form',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = Validator::make($request->all(), [
            'nama' => 'required|max:255',
            'telpon' => 'required|max:255',
            'alamat' => 'required|max:255',
        ],$this->customMessages,$this->customeAttr);
        if ($v->fails())
        {
            $errorString = implode(",",$v->messages()->all());
            return redirect()->back()->withInput()->withError($errorString);
        }
        $data = $request->only('nama','telpon','alamat');
        try {
            $created = Supplier::create($data);
        } catch(\Exception $e) {
            return redirect()->back()->withInput()->withError('terjadi error,'.$e->getMessage());
        }
        return redirect()->route('supplier.index')->withSuccess('data berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [];
        $data['supplier'] = Supplier::find($id);
        return view('supplier.form',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $v = Validator::make($request->all(), [
            'nama' => 'required|max:255',
            'telpon' => 'required|max:255',
            'alamat' => 'required|max:255',
        ],$this->customMessages,$this->customeAttr);
        if ($v->fails())
        {
            $errorString = implode(",",$v->messages()->all());
            return redirect()->back()->withInput()->withError($errorString);
        }
        $data = $request->only('nama','telpon','alamat');
        $data['updated_at'] = date('Y-m-d H:i:s');
        try {
            $row = Supplier::find($id);
            $row->fill($data);
            $saved = $row->save();
        } catch(\Exception $e) {
            return redirect()->back()->withInput()->withError('terjadi error');
        }
        return redirect()->route('supplier.index')->withSuccess('data berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Supplier = Supplier::find($id);
        $Supplier->delete();
        return redirect()->route('supplier.index')->withSuccess('data berhasil di hapus');
    }
}

resources/views/supplier/form.blade.php
@extends('app')
@section('content')
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
          Form Supplier
          <small></small>
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <!-- <h3 class="box-title">Data supplier</h3> -->
                        <div class="pull-right box-tools">
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        @if(session('success'))
                            <div class="alert alert-success" role="alert">
                                <span>{{session('success')}}</span>
                            </div>
                        @endif
                        @if(session('error'))
                            <div class="alert alert-danger" role="alert">
                                <span>{{session('error')}}</span>
                            </div>
                        @endif
                        @if (@$supplier)
                        <form id="form" action="{{route('supplier.update',$supplier->id)}}" method="post" role="form">
                        @else
                        <form id="form" action="{{route('supplier.store')}}" method="post" role="form">
                        @endif
                        @csrf
                        @if(@$supplier)
                            <input type="hidden" name="_method" value="put" />
                        @endif
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Nama </label>
                                <div class="col-xs-9">
                                <input class="form-control" required="" value="{{@$supplier->nama}}" name="nama" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">No.Telp </label>
                                <div class="col-xs-9">
                                <input class="form-control" required="" value="{{@$supplier->telpon}}" name="telpon" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Alamat </label>
                                <div class="col-xs-9">
                                <input class="form-control" required="" value="{{@$supplier->alamat}}" name="alamat" />
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <a href="{{route('supplier.index')}}"><button type="button" class="btn btn-default">Batal</button></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>
@endsection
@section('js')
    <script src="<?php echo url('assets'); ?>/pages/supplier.js" type="text/javascript"></script>
@endsection

resources/views/supplier/index.blade.php
@extends('app')
@section('content')
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
          Data Supplier
          <small></small>
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <!-- <h3 class="box-title">Data Supplier</h3> -->
                        <div class="pull-right box-tools">
                            <form class="form-inline">
                                <!-- <div class='input-group date' id='datepicker'>
                                    <input type='text' readonly="" value="<?php echo date('01-m-Y') ?>" name="filtertanggal" class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>&nbsp;&nbsp;<b>-</b>&nbsp;
                                <div class='input-group date' id='datepicker'>
                                    <input type='text' readonly="" value="<?php echo date('t-m-Y') ?>" name="filtertanggal1" class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>&nbsp;
                                <button class="btn btn-success btn-sm" type="button" id="btn-excel">Excel</button>-->
                                <a href="{{route('supplier.create')}}"><button class="btn btn-success btn-sm" type="button">Tambah</button></a>
                            </form>
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body table-responsive">
                        <table id="table" class="table table-bordered table-hover" style="width: 100%;">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>No.Telp</th>
                                    <th>Alamat</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                            @php
                                $i = 1;
                            @endphp
                            @foreach ($datas as $data)
                                <tr>
                                    <td>{{$i++}}</td>
                                    <td>{{$data->nama}}</td>
                                    <td>{{$data->telpon}}</td>
                                    <td>{{$data->alamat}}</td>
                                    <td>
                                        <a href="{{route('supplier.edit', $data->id)}}"> <i class="fa fa-edit text-warning" title="Edit Supplier"></i></a>
                                        <a data-toggle="modal" data-target="#deleteModal" data-action="{{route('supplier.destroy', $data->id)}}"> <i class="fa fa-trash-o text-danger" title="Hapus Supplier"></i>  </a>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div>
        </div>
        <div class="modal" tabindex="-1" role="dialog" id="deleteModal">
            <div class="modal-dialog" role="document">
                <form method="post" action="" id="deleteModalForm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Hapus Supplier ?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>
                                Anda yakin untuk menghapus supplier ini?
                            </p>
                            {{csrf_field()}}
                            <input type="hidden" name="_method" value="DELETE" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                            <button type="submit" class="btn btn-primary">Hapus</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->
@endsection
@section('js')
    <script src="<?php echo url('assets'); ?>/pages/supplier.js" type="text/javascript"></script>
@endsection