routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => true,
    'reset' => true,
    'login'=>false
]);

Route::get('/login', 'Auth\LoginController@showLoginForm')->name("login");
Route::post('/login', 'Auth\LoginController@login')->name("postlogin");
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', function () {
        return redirect()->route('home');
    });
	Route::get('/','HomeController@index')->name('home');
	Route::get('/profile','HomeController@indexProfile');
	Route::post('/profile','HomeController@storeProfile');
    Route::resource('barang','BarangController');
    Route::post('barang-import','BarangController@import')->name('import.barang');
    Route::resource('supplier','SupplierController');
    Route::resource('tipe','TipeController');
    Route::resource('user','UserController');
    Route::resource('forecasting','ForecastingController');
    Route::get('laporan_persediaan','PersediaanController@index');
    Route::get('laporan_persediaan/export_persediaan', 'PersediaanController@exportExcel')->name('persediaan.export');
    Route::get('laporan_persediaan/export_persediaan/all', 'PersediaanController@exportExcelAll')->name('persediaan.export.all');
    Route::get('laporan_penjualan','PenjualanController@index')->name('penjualan.index');
    Route::get('laporan_penjualan/create','PenjualanController@create')->name('penjualan.create');
    Route::post('laporan_penjualan/store','PenjualanController@store')->name('penjualan.store');
    Route::get('laporan_penjualan/edit/{id}','PenjualanController@edit')->name('penjualan.edit');
    Route::put('laporan_penjualan/update/{id}','PenjualanController@update')->name('penjualan.update');
    Route::post('laporan_penjualan/import','PenjualanController@import')->name('laporan_penjualan.import');
    Route::resource('laporan_pembelian','PembelianController');
    Route::get('export_pembelian', 'PembelianController@exportExcel')->name('pembelian.export');
    Route::get('export_pembelian/all', 'PembelianController@exportExcelAll')->name('pembelian.export.all');

    // Permisison
    Route::get('permission','PermissionController@index');
    Route::post('permission/request','PermissionController@requestPermission')->name('permission.request');
    Route::get('permission/accept/{id}','PermissionController@acceptPermission')->name('permission.accepted');
    Route::get('permission/decline/{id}','PermissionController@declinePermission')->name('permission.declined');
});

app/Models/Barang.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Barang extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $table = 'barang';
    protected $fillable = [
        'nama','sku','harga_jual','harga_beli','stock','tipe_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
    ];

    public function scopeSearch($query, $search){
        if ($search){
            return $query->whereRaw("(upper(nama) like '%". strtoupper($search) ."%')");
        }
    }

    public function tipe()
    {
        return $this->belongsTo("App\Models\Tipe");
    }
}

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Tipe;
use App\Models\Barang;
use App\Imports\BarangImport;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Validator;

class BarangController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */

    protected $customMessages = [
        'required' => ':attribute Harus Diisi',
        'unique' => ':attribute Sudah Ada Didatabase',
        'max' => ':attribute Max :max Digit',
        'min' => ':attribute Minimal :min',
        'mimes' => ':attribute Harus Format .xls atau .xlsx',
    ];
    protected $customeAttr = [
        'nama' => 'Nama',
        'sku'=>'Sku',
        'harga_jual'=>'Harga Jual',
        'harga_beli'=>'Harga Beli',
        'stock'=>'Stock',
        'tipe_id'=>'Tipe',
        'file' => 'File',
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['datas'] = Barang::get();
        return view('barang.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        $data['tipes'] = Tipe::get();
        return view('barang.form',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = Validator::make($request->all(), [
            'nama' => 'required|max:255',
            'sku' => 'required|max:255',
            'harga_jual' => 'required|max:255',
            'harga_beli' => 'required|max:255',
            'stock' => 'required|max:255',
            'tipe_id' => 'required|max:255',
        ],$this->customMessages,$this->customeAttr);
        if ($v->fails())
        {
            $errorString = implode(",",$v->messages()->all());
            return redirect()->back()->withInput()->withError($errorString);
        }
        $data = $request->only('nama','sku','harga_jual','harga_beli','stock','tipe_id');
        try {
            $created = Barang::create($data);
        } catch(\Exception $e) {
            return redirect()->back()->withInput()->withError('terjadi error,'.$e->getMessage());
        }
        return redirect()->route('barang.index')->withSuccess('data berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [];
        $data['tipes'] = Tipe::get();
        $data['barang'] = Barang::find($id);
        return view('barang.form',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $v = Validator::make($request->all(), [
            'nama' => 'required|max:255',
            'sku' => 'required|max:255',
            'harga_jual' => 'required|max:255',
            'harga_beli' => 'required|max:255',
            'stock' => 'required|max:255',
            'tipe_id' => 'required|max:255',
        ],$this->customMessages,$this->customeAttr);
        if ($v->fails())
        {
            $errorString = implode(",",$v->messages()->all());
            return redirect()->back()->withInput()->withError($errorString);
        }
        $data = $request->only('nama','sku','harga_jual','harga_beli','stock','tipe_id');
        $data['updated_at'] = date('Y-m-d H:i:s');
        try {
            $row = Barang::find($id);
            $row->fill($data);
            $saved = $row->save();
        } catch(\Exception $e) {
            return redirect()->back()->withInput()->withError('terjadi error');
        }
        return redirect()->route('barang.index')->withSuccess('data berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Barang = Barang::find($id);
        $Barang->delete();
        return redirect()->route('barang.index')->withSuccess('data berhasil di hapus');
    }

    public function import(Request $request)
    {
        $this->validate($request, [
            'file' => 'required|mimes:xls,xlsx'
        ], $this->customMessages,$this->customeAttr);

		$file = $request->file('file');

		$nama_file = rand().$file->getClientOriginalName();

		$file->move('barang',$nama_file);

        Excel::import(new BarangImport, public_path('/barang/'.$nama_file));

		return redirect()->back()->withSuccess('Berhasil import data excel');
    }
}

resources/views/barang/form.blade.php
@extends('app')
@section('content')
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
          Form Barang
          <small></small>
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <!-- <h3 class="box-title">Data barang</h3> -->
                        <div class="pull-right box-tools">
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        @if(session('success'))
                            <div class="alert alert-success" role="alert">
                                <span>{{session('success')}}</span>
                            </div>
                        @endif
                        @if(session('error'))
                            <div class="alert alert-danger" role="alert">
                                <span>{{session('error')}}</span>
                            </div>
                        @endif
                        @if (@$barang)
                        <form id="form" action="{{route('barang.update',$barang->id)}}" method="post" role="form">
                        @else
                        <form id="form" action="{{route('barang.store')}}" method="post" role="form">
                        @endif
                        @csrf
                        @if(@$barang)
                            <input type="hidden" name="_method" value="put" />
                        @endif
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Nama </label>
                                <div class="col-xs-9">
                                <input class="form-control" required="" value="{{@$barang->nama}}" name="nama" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">SKU </label>
                                <div class="col-xs-9">
                                <input class="form-control" required="" value="{{@$barang->sku}}" name="sku" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Harga Jual </label>
                                <div class="col-xs-9">
                                <input class="form-control only-numeric" required="" value="{{@$barang->harga_jual}}" name="harga_jual" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Harga Beli </label>
                                <div class="col-xs-9">
                                <input class="form-control only-numeric" required="" value="{{@$barang->harga_beli}}" name="harga_beli" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Tipe </label>
                                <div class="col-xs-9">
                                    <select class="form-control" required name="tipe_id">
                                        <option value="">Pilih Tipe</option>
                                        @foreach ($tipes as $tipe)
                                            <option @if($tipe->id == @$barang->tipe_id) selected @endif value="{{$tipe->id}}">{{$tipe->nama}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Stock </label>
                                <div class="col-xs-9">
                                <input class="form-control only-numeric" required="" value="{{@$barang->stock}}" name="stock" />
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <a href="{{route('barang.index')}}"><button type="button" class="btn btn-default">Batal</button></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>
@endsection
@section('js')
    <script src="<?php echo url('assets'); ?>/pages/barang.js" type="text/javascript"></script>
@endsection

resources/views/barang/index.blade.php
@extends('app')
@section('css')
<style>
.file-section {
    padding-top: 50px;
    padding-bottom: 50px;
}

.file-drop-area {
  position: relative;
  display: flex;
  align-items: center;
  width: 450px;
  max-width: 100%;
  padding: 25px;
  border: 1px dashed #2ecc71;
  border-radius: 3px;
  transition: 0.2s;
  margin: auto;
  right: 0;
  left: 0;
  &.is-active {
    background-color: rgba(255, 255, 255, 0.05);
  }
}

.fake-btn {
  flex-shrink: 0;
  background-color: #2ecc71;
  border: 1px solid #2ecc71;
  border-radius: 3px;
  padding: 8px 15px;
  margin-right: 10px;
  font-size: 12px;
  text-transform: uppercase;
  color: white;
  font-weight: bold;
}

#type-import {
  position: absolute;
  display: flex;
  align-items: center;
  width: 200px;
  max-width: 100%;
  border: 1px solid #2ecc71;
  border-radius: 3px;
  padding: 8px 15px;
  margin-right: 10px;
  font-size: 12px;
  text-transform: uppercase;
  color: #2ecc71;
  font-weight: bold;
  margin: auto;
  right: 58%;
  left: 0;
}

#type-import:focus {
    border-color: unset !important;
}

.file-msg {
  font-size: small;
  font-weight: 300;
  line-height: 1.4;
  white-space: nowrap;
  overflow: hidden;
  text-overflow: ellipsis;
}

.file-input {
  position: absolute;
  left: 0;
  top: 0;
  height: 100%;
  width: 100%;
  cursor: pointer;
  opacity: 0;
  &:focus {
    outline: none;
  }
}

.d-none {
    display:none !important;
}
</style>
@endsection
@section('content')
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
          Data Barang
          <small></small>
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    @if (Auth::user()->role != 'admin_penjualan')
                    <div class="box-header">
                        <!-- <h3 class="box-title">Data Barang</h3> -->
                        <div class="pull-right box-tools">
                            <form class="form-inline">
                                <!-- <div class='input-group date' id='datepicker'>
                                    <input type='text' readonly="" value="<?php echo date('01-m-Y') ?>" name="filtertanggal" class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>&nbsp;&nbsp;<b>-</b>&nbsp;
                                <div class='input-group date' id='datepicker'>
                                    <input type='text' readonly="" value="<?php echo date('t-m-Y') ?>" name="filtertanggal1" class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>&nbsp;
                                <button class="btn btn-success btn-sm" type="button" id="btn-excel">Excel</button>-->
                                <a class="btn btn-warning btn-sm d-none" id="cancel-to-import" style="color:white;">Batal</a>
                                <a class="btn btn-success btn-sm d-none" id="fake-btn" style="color:white;">Submit</a>
                                <a class="btn btn-success btn-sm" id="change-to-import" style="color:white;">Import</a>
                                <a href="{{route('barang.create')}}" id="add-btn"><button class="btn btn-primary btn-sm" type="button">Tambah</button></a>
                            </form>
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body d-none" id="section-import">
                        <form id="form" action="{{route('import.barang')}}" method="post" role="form" enctype="multipart/form-data">
                            @csrf
                            <div class="file-section">
                                <div class="file-drop-area">
                                    <span class="fake-btn">Choose files</span>
                                    <span class="file-msg">or drag and drop files here</span>
                                    <input class="file-input" type="file" name="file">
                                </div>
                                @if ($errors->has('file'))
                                    <span role="alert" style="color:#e74c3c;">
                                        <strong>* {{ $errors->first('file') }}</strong>
                                    </span>
                                @endif
                            </div>
                            <button class="btn btn-success btn-sm" type="submit" id="real-btn" style="display:none;">Import</button>
                        </form>
                    </div>
                    @endif

                    <div class="box-body table-responsive" id="section-table">
                        <table id="table" class="table table-bordered table-hover" style="width: 100%;">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Nama</th>
                                    <th>SKU</th>
                                    <th>Harga Jual</th>
                                    <th>Harga Beli</th>
                                    <th>Tipe</th>
                                    <th>Stock</th>
                                    @if (Auth::user()->role != 'admin_penjualan')
                                    <th>Aksi</th>
                                    @endif
                                </tr>
                            </thead>
                            <tbody>
                            @php
                                $i = 1;
                            @endphp
                            @foreach ($datas as $data)
                                <tr>
                                    <td>{{$i++}}</td>
                                    <td>{{$data->nama}}</td>
                                    <td>{{$data->sku}}</td>
                                    <td>{{number_format($data->harga_jual,0,"",".")}}</td>
                                    <td>{{number_format($data->harga_beli,0,"",".")}}</td>
                                    <td>{{@$data->tipe->nama}}</td>
                                    <td>{{$data->stock}}</td>
                                    @if (Auth::user()->role != 'admin_penjualan')
                                    <td>
                                        <a href="{{route('barang.edit', $data->id)}}"> <i class="fa fa-edit text-warning" title="Edit Barang"></i></a>
                                        <a data-toggle="modal" data-target="#deleteModal" data-action="{{route('barang.destroy', $data->id)}}"> <i class="fa fa-trash-o text-danger" title="Hapus Barang"></i>  </a>
                                    </td>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div>
        </div>
        <div class="modal" tabindex="-1" role="dialog" id="deleteModal">
            <div class="modal-dialog" role="document">
                <form method="post" action="" id="deleteModalForm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Hapus Barang ?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>
                                Anda yakin untuk menghapus barang ini?
                            </p>
                            {{csrf_field()}}
                            <input type="hidden" name="_method" value="DELETE" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                            <button type="submit" class="btn btn-primary">Hapus</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->
@endsection
@section('js')
    <script src="<?php echo url('assets'); ?>/pages/barang.js" type="text/javascript"></script>
    <script>
        var $fileInput = $('.file-input');
        var $droparea = $('.file-drop-area');

        $fileInput.on('dragenter focus click', function() {
            $droparea.addClass('is-active');
        });

        $fileInput.on('dragleave blur drop', function() {
            $droparea.removeClass('is-active');
        });

        $fileInput.on('change', function() {
            var filesCount = $(this)[0].files.length;
            var $textContainer = $(this).prev();

            if (filesCount === 1) {
                var fileName = $(this).val().split('\\').pop();
                $textContainer.text(fileName);
            } else {
                $textContainer.text(filesCount + ' files selected');
            }
        });

        $('#fake-btn').click(function() {
            $('#real-btn').click();
        })

        $('#change-to-import').click(function() {
            $('#section-table').addClass('d-none');
            $('#change-to-import').addClass('d-none');
            $('#add-btn').addClass('d-none');
            $('#section-import').removeClass('d-none');
            $('#cancel-to-import').removeClass('d-none');
            $('#fake-btn').removeClass('d-none');
        })

        $('#cancel-to-import').click(function() {
            $('#section-import').addClass('d-none');
            $('#fake-btn').addClass('d-none');
            $('#cancel-to-import').addClass('d-none');
            $('#section-table').removeClass('d-none');
            $('#change-to-import').removeClass('d-none');
            $('#add-btn').removeClass('d-none');
        })
    </script>
@endsection