routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes([
    'register' => false,
    'verify' => true,
    'reset' => true,
    'login'=>false
]);

Route::get('/login', 'Auth\LoginController@showLoginForm')->name("login");
Route::post('/login', 'Auth\LoginController@login')->name("postlogin");
Route::get('/logout', 'Auth\LoginController@logout');
Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', function () {
        return redirect()->route('home');
    });
	Route::get('/','HomeController@index')->name('home');
	Route::get('/profile','HomeController@indexProfile');
	Route::post('/profile','HomeController@storeProfile');
    Route::resource('barang','BarangController');
    Route::post('barang-import','BarangController@import')->name('import.barang');
    Route::resource('supplier','SupplierController');
    Route::resource('tipe','TipeController');
    Route::resource('user','UserController');
    Route::resource('forecasting','ForecastingController');
    Route::get('laporan_persediaan','PersediaanController@index');
    Route::get('laporan_persediaan/export_persediaan', 'PersediaanController@exportExcel')->name('persediaan.export');
    Route::get('laporan_persediaan/export_persediaan/all', 'PersediaanController@exportExcelAll')->name('persediaan.export.all');
    Route::get('laporan_penjualan','PenjualanController@index')->name('penjualan.index');
    Route::get('laporan_penjualan/create','PenjualanController@create')->name('penjualan.create');
    Route::post('laporan_penjualan/store','PenjualanController@store')->name('penjualan.store');
    Route::get('laporan_penjualan/edit/{id}','PenjualanController@edit')->name('penjualan.edit');
    Route::put('laporan_penjualan/update/{id}','PenjualanController@update')->name('penjualan.update');
    Route::post('laporan_penjualan/import','PenjualanController@import')->name('laporan_penjualan.import');
    Route::resource('laporan_pembelian','PembelianController');
    Route::get('export_pembelian', 'PembelianController@exportExcel')->name('pembelian.export');
    Route::get('export_pembelian/all', 'PembelianController@exportExcelAll')->name('pembelian.export.all');

    // Permisison
    Route::get('permission','PermissionController@index');
    Route::post('permission/request','PermissionController@requestPermission')->name('permission.request');
    Route::get('permission/accept/{id}','PermissionController@acceptPermission')->name('permission.accepted');
    Route::get('permission/decline/{id}','PermissionController@declinePermission')->name('permission.declined');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    public $table = 'user';
    protected $fillable = [
        'name', 'username', 'password','role'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Validator;

class UserController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('owner');
    }

    protected $customMessages = [
        'required' => ':attribute Harus Diisi',
        'unique' => ':attribute Sudah Ada Didatabase',
        'max' => ':attribute Max :max Digit',
        'min' => ':attribute Minimal :min',
    ];
    protected $customeAttr = [
        'username' => 'Username',
        'name' => 'Name',
        'password' => 'Password',
        'role' => 'Role',
        'is_active' => 'Active',
    ];
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [];
        $data['datas'] = User::get();
        return view('user.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = [];
        return view('user.form',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $v = Validator::make($request->all(), [
            'name' => 'required|max:255',
            'username' => 'required|max:255|unique:user,username,0,id',
            'password' => 'required|max:255',
            'role' => 'required|max:255',
        ],$this->customMessages,$this->customeAttr);
        if ($v->fails())
        {
            $errorString = implode(",",$v->messages()->all());
            return redirect()->back()->withInput()->withError($errorString);
        }
        $data = $request->only('name','role','username');
        if ($request->password) {
            $data['password'] = bcrypt($request->password);
        }
        try {
            $created = User::create($data);
        } catch(\Exception $e) {
            return redirect()->back()->withInput()->withError('terjadi error,'.$e->getMessage());
        }
        return redirect()->route('user.index')->withSuccess('data berhasil disimpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = [];
        $data['user'] = User::find($id);
        return view('user.form',$data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $v = Validator::make($request->all(), [
            'username' => 'required|max:255|unique:user,username,'.$id.',id',
            'name' => 'required|max:255',
            'role' => 'required|max:255',
        ],$this->customMessages,$this->customeAttr);
        if ($v->fails())
        {
            $errorString = implode(",",$v->messages()->all());
            return redirect()->back()->withInput()->withError($errorString);
        }
        $data = $request->only('name','role','username');
        if ($request->password) {
            $data['password'] = bcrypt($request->password);
        }
        $data['updated_at'] = date('Y-m-d H:i:s');
        try {
            $row = User::find($id);
            $row->fill($data);
            $saved = $row->save();
        } catch(\Exception $e) {
            return redirect()->back()->withInput()->withError('terjadi error');
        }
        return redirect()->route('user.index')->withSuccess('data berhasil di update');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $user = User::find($id);
        $user->delete();
        return redirect()->route('user.index')->withSuccess('data berhasil di hapus');
    }
}

resources/views/user/form.blade.php
@extends('app')
@section('content')
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
          Form User
          <small></small>
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box box-primary">
                    <div class="box-header">
                        <!-- <h3 class="box-title">Data User</h3> -->
                        <div class="pull-right box-tools">
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        @if(session('success'))
                            <div class="alert alert-success" role="alert">
                                <span>{{session('success')}}</span>
                            </div>
                        @endif
                        @if(session('error'))
                            <div class="alert alert-danger" role="alert">
                                <span>{{session('error')}}</span>
                            </div>
                        @endif
                        @if (@$user)
                        <form id="form" action="{{route('user.update',$user->id)}}" method="post" role="form">
                        @else
                        <form id="form" action="{{route('user.store')}}" method="post" role="form">
                        @endif
                        @csrf
                        @if(@$user)
                            <input type="hidden" name="_method" value="put" />
                        @endif
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Username </label>
                                <div class="col-xs-9">
                                <input class="form-control" required="" value="{{@$user->username}}" name="username" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Nama Lengkap</label>
                                <div class="col-xs-9">
                                <input class="form-control" required="" value="{{@$user->name}}" name="name" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Password</label>
                                <div class="col-xs-9">
                                <input class="form-control" name="password" />
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="control-label col-xs-3">Role</label>
                                <div class="col-xs-9">
                                    <select class="form-control" required="" name="role">
                                        <option value="">Pilih Tipe</option>
                                        <option {{@$user->role == 'owner' ? 'selected' : ''}} value="owner">Owner</option>
                                        <option {{@$user->role == 'admin_gudang' ? 'selected' : ''}} value="admin_gudang">Admin Gudang</option>
                                        <option {{@$user->role == 'admin_penjualan' ? 'selected' : ''}} value="admin_penjualan">Admin Penjualan</option>
                                    </select>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Simpan</button>
                            <a href="{{route('user.index')}}"><button type="button" class="btn btn-default">Batal</button></a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>
@endsection
@section('js')
    <script src="<?php echo url('assets'); ?>/pages/user.js" type="text/javascript"></script>
@endsection

resources/views/user/index.blade.php
@extends('app')
@section('content')
<!-- Right side column. Contains the navbar and content of the page -->
<aside class="right-side">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
          Data User
          <small></small>
        </h1>
    </section>

    <!-- Main content -->
    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <!-- <h3 class="box-title">Data User</h3> -->
                        <div class="pull-right box-tools">
                            <form class="form-inline">
                                <!-- <div class='input-group date' id='datepicker'>
                                    <input type='text' readonly="" value="<?php echo date('01-m-Y') ?>" name="filtertanggal" class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>&nbsp;&nbsp;<b>-</b>&nbsp;
                                <div class='input-group date' id='datepicker'>
                                    <input type='text' readonly="" value="<?php echo date('t-m-Y') ?>" name="filtertanggal1" class="form-control" />
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-calendar"></span>
                                    </span>
                                </div>&nbsp;
                                <button class="btn btn-success btn-sm" type="button" id="btn-excel">Excel</button>-->
                                <a href="{{route('user.create')}}"><button class="btn btn-success btn-sm" type="button">Tambah</button></a>
                            </form>
                        </div>
                    </div><!-- /.box-header -->
                    <div class="box-body table-responsive">
                        <table id="table" class="table table-bordered table-hover" style="width: 100%;">
                            <thead>
                                <tr>
                                    <th>No</th>
                                    <th>Username</th>
                                    <th>Nama</th>
                                    <th>Hak Akses</th>
                                    <th>Aksi</th>
                                </tr>
                            </thead>
                            <tbody>
                            @php
                                $i = 1;
                            @endphp
                            @foreach ($datas as $data)
                                <tr>
                                    <td>{{$i++}}</td>
                                    <td>{{$data->username}}</td>
                                    <td>{{$data->name}}</td>
                                    <td>{{$data->role}}</td>
                                    <td>
                                        <a href="{{route('user.edit', $data->id)}}"> <i class="fa fa-edit text-warning" title="Edit User"></i></a>
                                        @if ($data->id != 1)
                                            <a data-toggle="modal" data-target="#deleteModal" data-action="{{route('user.destroy', $data->id)}}"> <i class="fa fa-trash-o text-danger" title="Hapus User"></i>  </a>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div>
        </div>
        <div class="modal" tabindex="-1" role="dialog" id="deleteModal">
            <div class="modal-dialog" role="document">
                <form method="post" action="" id="deleteModalForm">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Hapus User ?</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <p>
                                Anda yakin untuk menghapus user ini?
                            </p>
                            {{csrf_field()}}
                            <input type="hidden" name="_method" value="DELETE" />
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                            <button type="submit" class="btn btn-primary">Hapus</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </section><!-- /.content -->
</aside><!-- /.right-side -->
@endsection
@section('js')
    <script src="<?php echo url('assets'); ?>/pages/user.js" type="text/javascript"></script>
@endsection